### PR TITLE
replace triu by triu_indices

### LINKED ISSUE #246: ElasticTensor bug when use_pressure=False
**Summary**
Elastic Tensor jobs work using pressure, but not using energy my strructures. When the "use_pressure" = False option is set they throw:

```python
_fit_coeffs_with_energies(strain, energy, volume, rotations, max_polynomial_order, fit_first_order)
    150     coeff = np.triu(np.ones((6,6))).flatten()
    151     # Multiply upper triangle with upper triangle coeffs (v.s.)
--> 152     coeff[coeff!=0] *= reg.coef_[:21]*eV_div_A3_to_GPa
    153     coeff = coeff.reshape(6,6)
    154     coeff = 0.5*(coeff+coeff.T)

ValueError: operands could not be broadcast together with shapes (21,) (18,) (21,) 
```

**Steps to Reproduce**

Run a ElasticTensor calculation with the attached structure (lammps format, original atom types are Cu and Zr, but that shouldn't matter I guess) using the use_pressure=False option.
[structure.txt](https://github.com/pyiron/pyiron_atomistics/files/6709559/structure.txt)

### PR DESCRIPTION
**Pull request by samwaseda**
Closes #246

### CODE REVIEW

**Comment by pmrv** [comment]
As discussed in #246 I've tried all combinations of running the job for an HCP cell.  Results are below first as matrices then as bar plots.

Generally orthorhombic structures seem to work best, but notice in the bar plot the inconsistency between c31 and c32 w/ pressure and c44 and c55 w/o pressure, which are supposed to be equal in HCP.

cij_bar
cij_matshow

**Comment by samwaseda** [comment]
> As discussed in #246 I've tried all combinations of running the job for an HCP cell. Results are below first as matrices then as bar plots.
> 
> Generally orthorhombic structures seem to work best, but notice in the bar plot the inconsistency between c31 and c32 w/ pressure and c44 and c55 w/o pressure, which are supposed to be equal in HCP.

For primitive I have frankly no idea why it's not working. Otherwise is it possible that the lattice parameter is not relaxed beforehand?

**Comment by pmrv** [comment]
> > As discussed in #246 I've tried all combinations of running the job for an HCP cell. Results are below first as matrices then as bar plots.
> > Generally orthorhombic structures seem to work best, but notice in the bar plot the inconsistency between c31 and c32 w/ pressure and c44 and c55 w/o pressure, which are supposed to be equal in HCP.
> 
> For primitive I have frankly no idea why it's not working. Otherwise is it possible that the lattice parameter is not relaxed beforehand?

I relaxed all the structures with `calc_minimize(pressure=[0]*6, ionic_force_tolerance=1e-6)` beforehand.

**Comment by samwaseda** [comment]
> I relaxed all the structures with `calc_minimize(pressure=[0]*6, ionic_force_tolerance=1e-6)` beforehand.

hm ok then I'm going to include a symmetrisation step

**Comment by samwaseda** [comment]
I realised that it's related to the fact that the point group symmetries that spglib do not help us symmetrize those values, so that for now it can be only avoided by increasing the number of points. In theory I guess it's possible to solve this problem by reducing the structure to the smallest unit and get all the symmetries there, but I'm not really sure how to do it properly. One way or other, this is more a fundamental problem, which is not directly related to this PR, so I'd suggest to merge this one and open another one as soon as we find a solution.

**Review by Leimeroth — APPROVED** [review]

**Comment by pmrv** [comment]
> I realised that it's related to the fact that the point group symmetries that spglib do not help us symmetrize those values, so that for now it can be only avoided by increasing the number of points. In theory I guess it's possible to solve this problem by reducing the structure to the smallest unit and get all the symmetries there, but I'm not really sure how to do it properly. One way or other, this is more a fundamental problem, which is not directly related to this PR, so I'd suggest to merge this one and open another one as soon as we find a solution.

I think both spglib and pymatgen have methods to get reduced unit cells from super cells, but I haven't looked into how they work.  If increasing the number of points works, should we just bump the default value for that?

**Pull request merged**
