### PR TITLE
Fix ase selective dynamics read bug

### PR DESCRIPTION
**Pull request by ligerzero-ai**
#932 replaces read() in StructureFactory with pymatgen reader which handles selective dynamics properly.

### CODE REVIEW

**Comment by jan-janssen** [comment]
> #932 replaces read() in StructureFactory with pymatgen reader which handles selective dynamics properly.

I am surprised, does `pymatgen` supports the same range of input/ output files like `ase` ? maybe we should add an additional parameter. https://databases.fysik.dtu.dk/ase/ase/io/io.html#ase.io.write

**Comment by ligerzero-ai** [comment]
pymatgen has openbabel as an optional dependency, and with it, it supports 113 file formats used in the chemistry community https://openbabel.org/docs/2.3.0/FileFormats/Overview.html

Fairly certain that pymatgen is therefore a more extensive reader, if you include openbabel as a dependency. How to proceed? Raise an error when selective dynamics is present? Or default to the pymatgen reader, and try ase where it fails?

**Comment by jan-janssen** [comment]
From my experience, `openbabel` an be pretty annoying in terms of dependencies and I am not sure how much overlap the computational chemistry and the computational materials science codes have. In particular as the computational chemistry codes need the bond definitions and so on, which at least currently is not supported in pyiron, as we internally rely on the ASE structure. 

Still I am open to add multiple read functions like `read_with_ase()` and `read_with_pymatgen()` and so on. Then we only have to clarify which one we set as default. At the same time as your changes already break the jupyter notebooks, switching from ASE to pymatgen as primary reader breaks the backwards compatibility. 

Finally, we could also consider fixing the bug on the ASE side.

**Comment by ligerzero-ai** [comment]
@jan-janssen newest changes ok to merge?

**Review by jan-janssen — APPROVED** [review]
Looks good to me

**Comment by jan-janssen** [comment]
> @jan-janssen newest changes ok to merge?

Yes

**Pull request merged**
