### PR TITLE
Automatically set interactive_enforce_structure_reset, when setting s…

### PR DESCRIPTION
**Pull request by pmrv**
…tructure of different length

Also changes explicit calls to superclass getters/setters to super

### CODE REVIEW

**Comment by samwaseda** [comment]
To be honest I have the feeling that we're actually only smothering the consequence of a much larger problem... I guess at some point we should think of how to see what to update more in detail.

**Comment by pmrv** [comment]
I'm open to suggestions, it's just that I feel I shouldn't be bothered to remember typing this all the time. :')

**Comment by jan-janssen** [comment]
But the super calls are not the same.

**Comment by pmrv** [comment]
> But the super calls are not the same.

Yep, teaches me not to do too many things at once. :/ I'll remove those again.

**Comment by pmrv** [comment]
From the meeting: change instead `GenericInteractive.run_if_interactive:133`.

**Pull request closed without merging**
