### PR TITLE
Use ResourceResolvers in lammps/vasp/sphinx

### PR DESCRIPTION
**Pull request by pmrv**
Minimal changes to make atomistics use the resolvers.  See #1528 for clean up.

### CODE REVIEW

**Comment by pmrv** [comment]
Test failure was due to the backwards version testing.  I've updated `environment-old.yml`, but not sure if that's all it takes to propagate that change to packaging.

**Review by samwaseda — APPROVED** [review]
If it passes the integration tests I'm fine.

**Review by jan-janssen — APPROVED** [review]
Looks good to me

**Comment by pmrv** [comment]
Like I wrote in #1528 and I added those commits here now as well.

@jan-janssen Is changing `environment-old.yml` enough to update the version bounds in the packages or do I need to change something else as well?

**Comment by jan-janssen** [comment]
> @jan-janssen Is changing `environment-old.yml` enough to update the version bounds in the packages or do I need to change something else as well?

Updating the  `environment-old.yml` is sufficient. The information is combined in the https://github.com/pyiron/pyiron_atomistics/blob/main/.ci_support/release.py script which is called in https://github.com/pyiron/pyiron_atomistics/blob/main/.github/workflows/deploy.yml

**Pull request merged**
