### PR TITLE
Allow hcp 4-axes indices as well

### LINKED ISSUE #388: Atomsk Wrapper can't deal with hcp structures
Axes orientations are currently checked to be 3x3, but for hexagonal they may also be 4x4.  Should be a quick fix, just a reminder for myself.

### PR DESCRIPTION
**Pull request by pmrv**
@prince-mathews Give this a try if it works for HCP Mg now.

### CODE REVIEW

**Comment by prince-mathews** [comment]
@pmrv Thank you for including the 4-axes indices. The input hkl for hcp structures should be a 3x4 matrix so I have changed it in the file.

**Comment by prince-mathews** [comment]
Should I merge it?

**Comment by pmrv** [comment]
> Should I merge it?

Have you tried it on the cluster once?  Because I didn't.  If it works, merge it.

**Comment by prince-mathews** [comment]
> > Should I merge it?
> 
> Have you tried it on the cluster once? Because I didn't. If it works, merge it.

How do I try it on the cluster? It's not in the master branch yet. Can I try it without it being merged?

**Comment by pmrv** [comment]
Atomsk on the cluster is currently [out-of-date](https://github.com/conda-forge/atomsk-feedstock/pull/16).

**Comment by pmrv** [comment]
> > > Should I merge it?
> > 
> > 
> > Have you tried it on the cluster once? Because I didn't. If it works, merge it.
> 
> How do I try it on the cluster? It's not in the master branch yet. Can I try it without it being merged?

I found a few bugs testing it, I'll give it a try again once the conda package is updated.

We have some older instructions [here](https://gitlab.mpcdf.mpg.de/eisenforschung/cm/documentation/-/blob/master/Cluster.md#Pyiron-Development-On-CMTI) how to set up a dev environment, just replace the `pyiron` repo name with `pyiron_atomistics`.

**Pull request merged**
