### PR TITLE
To set the convergence precision properly in sphinx jobs

### LINKED ISSUE #578: Setting convergence precision in sphinx jobs
I am trying to set convergence precision using the function set_convergence_precision function and cal_minimize for sphinx jobs. However, I do not get what I intend to do. Below I am showing three code snippets and their corresponding outputs. 

```python
job = pr.create_job(
          job_type=pr.job_type.Sphinx,
          job_name='test'
          )
job.structure = pr.create_ase_bulk('Al','fcc',3.5)
job.set_convergence_precision(electronic_energy=1e-8, ionic_energy_tolerance=1e-1)
```
output:
```python
print(job.input.sphinx.main.ricQN.dEnergy) #0.0036
print(job.input.sphinx.main.ricQN.bornOppenheimer.scfDiag.dEnergy)#3.6e-06
```

Case 1, sets the ionic energy tolerance correctly but does not set the electronic energy correctly.
 
CASE 2:
```python
job = pr.create_job(
          job_type=pr.job_type.Sphinx,
          job_name='test'
          )
job.structure = pr.create_ase_bulk('Al','fcc',3.5)
job.set_convergence_precision(electronic_energy=1e-8)
job.set_convergence_precision(ionic_energy_tolerance=1e-1)
```
output:
```python
print(job.input.sphinx.main.ricQN.dEnergy) #0.003674
print(job.input.sphinx.main.ricQN.bornOppenheimer.scfDiag.dEnergy) #3.6e-10
```

In case 2, if I call the set_convergence function twice first with only electronic_energy as the parameter and then the second time with only ionic_energy_tolerance as the parameter, it sets the values correctly. However, if I switch the order i.e., I set the ionic_energy_tolerance first and then electronic_energy. The electronic energy is not properly set in the input.

CASE 3:
```python
job = pr.create_job(
          job_type=pr.job_type.Sphinx,
          job_name='test'
          )
job.structure = pr.create_ase_bulk('Al','fcc',3.5)
job.calc_minimize(ionic_steps=100,electronic_steps=100)
job.set_convergence_precision(ionic_energy_tolerance=1e-1,electronic_energy=1e-8)
```
Output:
```python
print(job.input.sphinx.main.ricQN.dEnergy) #3.6e-05
print(job.input.sphinx.main.ricQN.bornOppenheimer.scfDiag.dEnergy)#3.6e-06
```

Finally in case 3 (which is basically what I would like to do), I would set the number of ionic steps and electronic steps using calc_minimize and then set_convergence_precision. This, however, does not set either value to what I intend. However, if I reverse the order in which they are called, the electronic_energy alone is correctly set.

I think this might be a bug.

### PR DESCRIPTION
**Pull request by skatnagallu**
To properly set the convergence precisions for the sphinx jobs. To fix issue #578

### CODE REVIEW

**Comment by samwaseda** [comment]
Great! There are a few things that you might be take a look at, to get used to the full workflow of a PR.

- Link the issue from "Development" on the right hand side of this page
- Resolve conflicts (which should be easy)
- Add tests.

Adding tests consists of editing [`test_base.py`](https://github.com/pyiron/pyiron_atomistics/blob/master/tests/sphinx/test_base.py). You can add something like:

```python
def test_energy_convergence(self):
    job = self.project.create.Sphinx('energy_convergence')
    ....
```

Here, in `....` you can put the failed cases that you raised in #578. You can do the comparisons with `self.assertAlmostEqual` with the values that you had expected to see. You can locally test the script to see if it passes. Before you start wondering, I'm sorry that there's one test that will probably fail on your local environment, because the pseudo-potential files are different from what's on the GitHub testing environment. But other than that, if your test goes through, you're good to go.

**Comment by skatnagallu** [comment]
@samwaseda I still could not figure out the problem completely. Calling `calc_minimize()` in the end without the ionic_energy_tolerence argument, sets the values to 0.0, which I do not understand why. Could you have a look?

**Comment by samwaseda** [comment]
> @samwaseda I still could not figure out the problem completely. Calling `calc_minimize()` in the end without the ionic_energy_tolerence argument, sets the values to 0.0, which I do not understand why. Could you have a look?

Ah actually that's because it's defined in [`interactive.py`](https://github.com/pyiron/pyiron_atomistics/blob/master/pyiron_atomistics/sphinx/interactive.py) as well. From my point of view, since there's no possibility to set `calc_minimize` in SPHInX when interactive, you can erase the function from `interactive.py` altogether.

**Comment by samwaseda** [comment]
It could also be helpful if you'd use different commit messages for different commits

**Comment by skatnagallu** [comment]
> It could also be helpful if you'd use different commit messages for different commits

Ah, sorry! I am a noob with git. I am adding new commit message at the end of old ones. I will keep this in mind. So I basically changed default values in `interactive.py` . One last thing is I did not understand this "This branch has conflicts that must be resolved
Use the [web editor](https://github.com/pyiron/pyiron_atomistics/pull/579/conflicts) or the to resolve conflicts.
Conflicting files". How can I solve this?

**Comment by samwaseda** [comment]
> One last thing is I did not understand this "This branch has conflicts that must be resolved Use the [web editor](https://github.com/pyiron/pyiron_atomistics/pull/579/conflicts) or the to resolve conflicts. Conflicting files". How can I solve this?

Here, you can simply click on "Resolve conflicts". Then you'll see the following lines (among a lot of other lines):

```python
<<<<<<< sphinxconv
            self.input.sphinx.main[optimizer]["maxStepLength"] = str(0.1/BOHR_TO_ANGSTROM)
=======
            self.input.sphinx.main[optimizer]["maxStepLength"] = str(
                0.1 / BOHR_TO_ANGSTROM
            )
            if "dE" in self.input and "dF" in self.input:
                self.input["dE"] = 1e-3
>>>>>>> master
```

This essentially means that in your `sphinxconv` branch you have the first line, while in the master branch there are the 5 lines that follow. GitHub doesn't know how to merge this part automatically, so it requires your intervention. In this case, as you can see you can erase what's written in the master branch and save the content. Don't forget to erase `<<<<<<< sphinxconv`, `=======` and `>>>>>>> master`

**Comment by samwaseda** [comment]
Brilliant! Finally, we try to stick to the PEP8 standards. This can be automatically done by activating `format_black` from the list of "Labels" on the right hand side.

**Review by samwaseda — APPROVED** [review]
Very good! When all the tests pass you can merge it :)

**Pull request merged**
