### PR TITLE
Make a proper unit conversion of bulk modulus in Murnaghan

### LINKED ISSUE #1014: Input / Output murnaghan - possible unit confusion
When we do a murn-fit like 
```# [e0, b0, bP, v0], [e0_error, b0_error, bP_error, v0_error] = murn._fit_leastsq(volume_lst, energy_lst,fittype='vinet')```
we have the units in eV, GPa, and Ang^3. 

However, when using the vinet equation as implemented (as in ase/eos.py)
```def vinet_energy(V, E0, B0, BP, V0):
    "Vinet equation from PRB 70, 224107"
    eta = (V / V0) ** (1 / 3)
    return E0 + 2 * B0 * V0 / (BP - 1) ** 2 * (
        2 - (5 + 3 * BP * (eta - 1) - 3 * eta) * np.exp(-3 * (BP - 1) * (eta - 1) / 2)
    )
```

The `B0` in there is defined as in ase in eV/Ang^3. The result is that one has to add a unit conversion factor as in 
https://pyiron.readthedocs.io/en/latest/source/notebooks/energy_volume_curve.html (eq. [15]).

I think this unit conversion is a bit confusing and one has to be careful in distinguishing units of variables for different modules / functions....

### PR DESCRIPTION
**Pull request by samwaseda**
Closes https://github.com/pyiron/pyiron_atomistics/issues/1014

Unit conversion of bulk modulus is now included.

### CODE REVIEW

**Comment by niklassiemer** [comment]
Did we use these functions anywhere in our code base? Not that we apply the conversion twice in that case. 

And they were used in some notebooks, weren't they?

**Comment by samwaseda** [comment]
> Did we use these functions anywhere in our code base? Not that we apply the conversion twice in that case.
> 
> And they were used in some notebooks, weren't they?

Good point, and indeed I missed it inside the file.

Although I have to say it's totally unclear what was meant to be visible to the outside and what wasn't in this file. The whole thing is a mess.

**Comment by jan-janssen** [comment]
This changes the data stored in the `Murnaghan` job. 
```
 def _fit_eos_general(self, vol_erg_dic=None, fittype="birchmurnaghan"):
        self._set_fit_module(vol_erg_dic=vol_erg_dic)
        fit_dict = self.fit_module.fit_eos_general(fittype=fittype)
        self.input["fit_type"] = fit_dict["fit_type"]
        self.input["fit_order"] = 0
        self._store_fit_in_hdf(fit_dict=fit_dict)
        self.fit_dict = fit_dict
        return fit_dict
```
Short - it breaks the backwards compatibility.

**Comment by samwaseda** [comment]
> Short - it breaks the backwards compatibility.

I need a bit more detail to understand why

**Comment by jan-janssen** [comment]
> > Short - it breaks the backwards compatibility.
> 
> I need a bit more detail to understand why

You change is what is stored in the `fit_dict` so that changes the `Murnaghan` class.

**Comment by samwaseda** [comment]
> You change is what is stored in the `fit_dict` so that changes the `Murnaghan` class.

I don't understand where I changed it.

**Comment by jan-janssen** [comment]
> > You change is what is stored in the `fit_dict` so that changes the `Murnaghan` class.
> 
> I don't understand where I changed it.

I see - that was my mistake - it is only set in line 528.

**Review by jan-janssen — APPROVED** [review]
Looks good to me

**Comment by samwaseda** [comment]
Since the original problem is bypassed with [this PR](https://github.com/pyiron/pyiron/pull/1479), I close this PR.

**Pull request closed without merging**
