### PR TITLE
Add Calphy Job

### PR DESCRIPTION
**Pull request by pmrv**
I rebased the murnaghan related commits out of #637, I don't have access to srmnitc:pyiron_atomistics, so I put a new PR.

For future reference, what I did was:
1. locate the offending commits with `git blame` and `git log`
2. Checkout srmnitc:pyiron_atomistics/master locally
3. `git rebase -i origin/master`
4. manually remove the commits identified in 1.

### CODE REVIEW

**Comment by pmrv** [comment]
@srmnitc Please double check that I haven't missed any commits.

As I said in #636, I think the revert was not necessary and this can be merged again directly.

**Comment by srmnitc** [comment]
> I rebased the murnaghan related commits out of #637, I don't have access to srmnitc:pyiron_atomistics, so I put a new PR.
> 
> For future reference, what I did was:
> 
>     1. locate the offending commits with `git blame` and `git log`
> 
>     2. Checkout srmnitc:pyiron_atomistics/master locally
> 
>     3. `git rebase -i origin/master`
> 
>     4. manually remove the commits identified in 1.

This is excellent, really appreciate the help.

**Comment by pmrv** [comment]
We are going to need this for the workshop right? If so, I'll merge today and we can trigger a new release.

**Comment by srmnitc** [comment]
@pmrv I had already released a version before which included the calphy job, before it was reverted. The workshop env still has this, so it has the calphy job. I say we keep it that way and only do a release after the workshop. I tested today morning and it seemed to work.

**Review by srmnitc — APPROVED** [review]

**Comment by srmnitc** [comment]
@pmrv I am getting some requests from the workshop participants asking why CalphyJob cannot be found in the new pyiron atomistics. I think its better to merge this in. The rest of the modifications I will simply open a new pull request. Could you please merge when you can?

**Pull request merged**
