### PR TITLE
:memo: Add new exception for calc_minimize.

### PR DESCRIPTION
**Pull request by KuhnMn**
Solution for #696.  Add a new exception to the calc_minimize method that is raised when pressure is about to be calculated while the rotation_matrix is None. This would raise an exception anyways, but with a more generic message.

### CODE REVIEW

**Comment by KuhnMn** [comment]
Hello, I am having some issues understanding the failing workflows.
From the logs, the issue in both cases seems to be that the setuptools_scm module is not found. However, I changed nothing regarding the packages or modules of the project. With this being my first contribution, I'd appreciate some help in fixing the pipeline issues.
Thank you in advance!

**Comment by jan-janssen** [comment]
Hi @KuhnMn , 

Unfortunately, we currently have an issue with the `mpi_api` package `pyiron_atomistics` depends on: 
https://github.com/pyiron/pyiron_base/issues/983

We are working on fixing this as soon as possible. 

Best, 

Jan

**Comment by KuhnMn** [comment]
Hi, @jan-janssen  

thank you for the clarification!

Best,

Maximilian

**Comment by jan-janssen** [comment]
It is fixed

**Comment by KuhnMn** [comment]
Thanks a lot, that resolved the last checks not passing!

**Review by jan-janssen — APPROVED** [review]
Looks good to me

**Pull request merged**
