### PR TITLE
Pickle atoms

### PR DESCRIPTION
**Pull request by liamhuber**
I'd like to be able to pickle atoms for the contrib workflow stuff. Right now the code below throws a recursion error, with this PR it works fine:

```python
import pickle

from pyiron_atomistics.atomistics.structure.factory import StructureFactory
struct = StructureFactory().bulk("Al")

with open("my_stored_structure", mode="wb") as f:
    pickle.dump(struct, f)
```

And then in a new interpreter instance:
```python
import pickle

with open("my_stored_structure", mode="rb") as f:
    loaded_struct = pickle.load(f)

loaded_struct.plot3d()
```

@pmrv, you are my storage expert -- am I being super naive here, or was specifying `__setstate__` really all we were missing??

### CODE REVIEW

**Comment by liamhuber** [comment]
Unit test failure:

```
ERROR: test_pickle (atomistics.structure.test_atoms.TestAtoms)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/pyiron_atomistics/pyiron_atomistics/tests/atomistics/structure/test_atoms.py", line 1957, in test_pickle
    pickled = pickle.dumps(self.C3)
TypeError: 'NoneType' object is not callable
```

Absolutely bizarre. `pickle` is imported at the head of the file, not mentioned anywhere else in the test file, and the module is part of the standard library. I have no idea how it's acting as `NoneType` here. Tests pass fine on my local machine.

**Comment by pmrv** [comment]
I did some [research](https://github.com/pyiron/pyiron_atomistics/pull/835), but never got to finish it.  The underlying issue was with the chemical objects.  Overloading `__{set,get}state__` on `Atoms` would indeed be one way to fix the issue, but then you'll need to take care that actually all of the additional information we can have on our `Atoms` is preserved, which would increase the test cases by a good amount.  My earlier attempt got quite involved though, so I have no strong preference to either solution as long as we don't loose information.

**Comment by liamhuber** [comment]
> but then you'll need to take care that actually all of the additional information we can have on our Atoms is preserve

For clarification, you mean the fields listed in lines [105](https://github.com/pyiron/pyiron_atomistics/blob/068d344997fb70239466da371b1b570270b8bbf4/pyiron_atomistics/atomistics/structure/atoms.py#L105) to 112? Or is there more hiding somewhere?

Ah, shoot, there's at least also [constraints](https://github.com/pyiron/pyiron_atomistics/blob/068d344997fb70239466da371b1b570270b8bbf4/pyiron_atomistics/atomistics/structure/atoms.py#LL122C12-L122C12) and [bonds](https://github.com/pyiron/pyiron_atomistics/blob/068d344997fb70239466da371b1b570270b8bbf4/pyiron_atomistics/atomistics/structure/atoms.py#L211) which might be non-trivial data.

>  ...which would increase the test cases by a good amount. 

I would be happy to extend the tests, but unfortunately none of the attributes I'm looking at are typed or documented. Something like `magmom` I can safely intuit as an `np.ndarray`, and I suspect that something like `calculator` is actually an `ase.Calculator` (or whatever/wherever they keep this class), but I am worried that whatever tests I come up with will not actually be any guarantee of the intended behaviour. 

Do you know of some sort of "worst-case structure" I might be able to use as a reference?

> My earlier attempt got quite involved though, so I have no strong preference to either solution as long as we don't loose information.

What I like about this solution is that it only touches `__setstate__`, which is a pickle-specific special method, so any changes on this have _zero_ impact on any other behaviour of `Atoms`. Ultimately, having no other serious personal problems with `Atoms`, and knowing it may (ought to!) simply get replaced with `ase.Atoms` in the near(?) future, I prefer the PR of least-action.

**Comment by liamhuber** [comment]
> Unit test failure:
> 
> ```
> ERROR: test_pickle (atomistics.structure.test_atoms.TestAtoms)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/home/runner/work/pyiron_atomistics/pyiron_atomistics/tests/atomistics/structure/test_atoms.py", line 1957, in test_pickle
>     pickled = pickle.dumps(self.C3)
> TypeError: 'NoneType' object is not callable
> ```
> 
> Absolutely bizarre. `pickle` is imported at the head of the file, not mentioned anywhere else in the test file, and the module is part of the standard library. I have no idea how it's acting as `NoneType` here. Tests pass fine on my local machine.

This is really insane. `pickle.dumps` is absolutely not `None`, so somehow the CI environment must have some other module-like object called `pickle` that _does_ have `dumps = None` and this is getting imported instead?!

**Comment by liamhuber** [comment]
> This is really insane. `pickle.dumps` is absolutely not `None`, so somehow the CI environment must have some other module-like object called `pickle` that _does_ have `dumps = None` and this is getting imported instead?!

The madness continues: tests for python 3.11 on ubuntu-latest are passing! But 3.9 on ubuntu-latest still fails.

My debug prints inside the CI have revealed that it is _not_ some weird module overload -- it is getting the module and method just fine:

```
"/home/runner/work/pyiron_atomistics/pyiron_atomistics/tests/atomistics/structure/test_atoms.py", line 1965, in test_pickle
    raise RuntimeError(
RuntimeError: pickle=<module 'pickle' from '/usr/share/miniconda3/envs/my-env/lib/python3.9/pickle.py'> (<class 'module'>, pickle.dumps=<built-in function dumps>, local files=['.coveragerc', '.coverage.fv-az1100-866.2578.657962', '.coverage.fv-az1100-866.2562.456149', 'CITATION.cff', '.coveralls.yml', '.readthedocs.yml', 'versioneer.py', 'environment.yml', 'setup.cfg', 'setup.py', '.coverage.fv-az1100-866.2549.560148', '.coverage.fv-az1100-866.2530.830376', '.coverage.fv-az1100-866.2535.423340', 'CODE_OF_CONDUCT.md', 'info.log', 'README.rst', 'pyiron.log', '.coverage.fv-az1100-866.2606.084357', '.gitattributes', 'get_structure_test.tar.gz', '.gitpod', '.gitignore', 'MANIFEST.in', 'export.csv', '.coverage.fv-az1100-866.2575.966032', '.coverage.fv-az1100-866.2592.676826', 'CHANGELOG.md', 'CONTRIBUTING.rst', 'LICENSE']
```

**Comment by jan-janssen** [comment]
As the ASE atoms are already pickle-able maybe this is another motivation to move to ASE atoms. This was one of the issues which lead to the development of https://github.com/pyiron/pyiron_lammps

**Comment by samwaseda** [comment]
> then you'll need to take care that actually all of the additional information we can have on our Atoms is preserved

Since the additional information is mostly stored in ASE arrays [with this PR](https://github.com/pyiron/pyiron_atomistics/pull/981), merging it might make it a bit easier to solve some of the problems here (even though I don't really understand what's the issue here).

**Comment by pmrv** [comment]
> > Unit test failure:
> > ```
> > ERROR: test_pickle (atomistics.structure.test_atoms.TestAtoms)
> > ----------------------------------------------------------------------
> > Traceback (most recent call last):
> >   File "/home/runner/work/pyiron_atomistics/pyiron_atomistics/tests/atomistics/structure/test_atoms.py", line 1957, in test_pickle
> >     pickled = pickle.dumps(self.C3)
> > TypeError: 'NoneType' object is not callable
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Absolutely bizarre. `pickle` is imported at the head of the file, not mentioned anywhere else in the test file, and the module is part of the standard library. I have no idea how it's acting as `NoneType` here. Tests pass fine on my local machine.
> 
> This is really insane. `pickle.dumps` is absolutely not `None`, so somehow the CI environment must have some other module-like object called `pickle` that _does_ have `dumps = None` and this is getting imported instead?!

Ah, behold the darkness that lurks within the long forgotten source (code).

If I remember correctly, this also came up during my debugging of the above PR.  The errors is actually from `pickle.dumps` trying to call `__setstate__/__getstate__` on `ChemicalElement` or related objects.  This class overloads `__getattr__` wrongly, so that trying to access `obj.__getstate__` returns `None`, which `pickle` then tries to call.  This is why you see me changing a lot of (seemingly) unrelated stuff in that PR and what made it so tricky.  Iirc, I mostly sorted it out, except for notebook tests, though.

**Comment by liamhuber** [comment]
> Ah, behold the darkness that lurks within the long forgotten source (code).
> 
> If I remember correctly, this also came up during my debugging of the above PR. The errors is actually from `pickle.dumps` trying to call `__setstate__/__getstate__` on `ChemicalElement` or related objects. This class overloads `__getattr__` wrongly, so that trying to access `obj.__getstate__` returns `None`, which `pickle` then tries to call. This is why you see me changing a lot of (seemingly) unrelated stuff in that PR and what made it so tricky. Iirc, I mostly sorted it out, except for notebook tests, though.

But then why is it working just fine on my local machine and for the py3.11 tests? They must have changed the underlying behaviour of `pickle` and the new behaviour seems to get around our `ChemicalElement` nonsense just fine...

EDIT: One of the things on my todo list today is to get a local py3.9 pyiron env set up (I usually work on 3.11) and see if I can reproduce it only my local with a full stack trace to work with!

**Comment by liamhuber** [comment]
> > then you'll need to take care that actually all of the additional information we can have on our Atoms is preserved
> 
> Since the additional information is mostly stored in ASE arrays [with this PR](https://github.com/pyiron/pyiron_atomistics/pull/981), merging it might make it a bit easier to solve some of the problems here (even though I don't really understand what's the issue here).

I am happy for anything that makes this easier, but I look at that PR and see zero "approves" so I will let the three of you sort that out first 😉

**Comment by liamhuber** [comment]
> As the ASE atoms are already pickle-able maybe this is another motivation to move to ASE atoms. This was one of the issues which lead to the development of https://github.com/pyiron/pyiron_lammps

I really like this, but I am still willing to proceed with this PR under the condition that it _only_ modifies `__setstate__` (and `__getstate__` and whatever other special magic methods pickle defines). My rationale is that such changes _only_ impact the new functionality of being pickle-able, so there should be no cross-contamination with the rest of the code base. At that point, it's a purely managerial question of whether it's worth spending my dev time implementing this temporary fix (including new tests to make sure that this new feature works and stays working), or to simply jump right into the `Atoms`->`ase.Atoms` conversion.

I made a discussion point for this at next weeks meeting, and opened draft PR #1037 as a place to play around with what the consequences of such a switch might look like. I think I'll play around with fixing up some of the tests over there, just to get a sense of how much work this transition might be, before digging any deeper into tests here.

**Comment by pmrv** [comment]
> > Ah, behold the darkness that lurks within the long forgotten source (code).
> > If I remember correctly, this also came up during my debugging of the above PR. The errors is actually from `pickle.dumps` trying to call `__setstate__/__getstate__` on `ChemicalElement` or related objects. This class overloads `__getattr__` wrongly, so that trying to access `obj.__getstate__` returns `None`, which `pickle` then tries to call. This is why you see me changing a lot of (seemingly) unrelated stuff in that PR and what made it so tricky. Iirc, I mostly sorted it out, except for notebook tests, though.
> 
> But then why is it working just fine on my local machine and for the py3.11 tests? They must have changed the underlying behaviour of `pickle` and the new behaviour seems to get around our `ChemicalElement` nonsense just fine...
> 
> EDIT: One of the things on my todo list today is to get a local py3.9 pyiron env set up (I usually work on 3.11) and see if I can reproduce it only my local with a full stack trace to work with!

It seems 3.11 introduced a default [`__getstate__`](https://docs.python.org/release/3.11.2/library/pickle.html#object.__getstate__), which probably side steps this.

**Comment by liamhuber** [comment]
> It seems 3.11 introduced a default [__getstate__](https://docs.python.org/release/3.11.2/library/pickle.html#object.__getstate__), which probably side steps this.

@pmrv, thanks for the really excellent pointer! I had read "Added the default implementation of the `__getstate__()` method in the `object` class.", but I just absolutely did not parse the significance of this. Explicitly adding very simply `__getstate__` methods on the three relevant classes following the spec in the docs you linked cleared up the test on my local machine with a py3.9 env, so I'm optimistic for the CI that's running now.

**Comment by liamhuber** [comment]
@samwaseda, as a Lammps guy,  I have never touched any of the extra tags and flags we can stick on `Atoms`. I have no reason to suspect that pickling these will fail, but could you suggest a nice test case where we slap on a spanning subset of such flags for a sanity check?

**Pull request merged**
