### PR TITLE
Selective dynamics in some directions of a VASP POSCAR in ASE Atoms is not supported (pymatgen Structure -> Atoms converter) pymatgen_to_pyiron(structure)

### LINKED ISSUE #786: Selective dynamics in some directions of a VASP POSCAR in ASE Atoms is not supported (pymatgen Structure -> Atoms converter) pymatgen_to_pyiron(structure)
Trying to set limited degrees of freedom is not supported in the ASE atoms object (e.g. Selective Dynamics with [ T T F ])

**Expected behaviour:**

It should accept this! Otherwise jobs with relaxations only in certain ionic directions is forbidden and kills entire workflows.

**To reproduce:**

```
import numpy as np
import os; import shutil
import pandas as pd

from pymatgen.io.vasp.inputs import Potcar, Incar, Kpoints
from pymatgen.core import Structure
from pymatgen.core.lattice import Lattice
from pymatgen.io.ase import AseAtomsAdaptor
import pymatgen.core.structure
from pymatgen.core.operations import SymmOp

from ase.lattice.cubic import FaceCenteredCubic as fcc
from ase.lattice.cubic import BodyCenteredCubic as bcc
from ase.build import stack, add_vacuum, fcc111, surface, bulk
from ase import build as build

from pyiron.project import Project
import pyiron.atomistics.structure.atoms as pi_atoms

Bulk = build.bulk('Ni', 'fcc', a = 3.518, cubic = True)
struct = AseAtomsAdaptor.get_structure(Bulk)
sd_list = [[False, False, True] for x in struct]
# Update the site dynamics list into the new siteproperties object
new_sp = struct.site_properties
new_sp['selective_dynamics'] = sd_list
# Apply the new site properties into the new structure
struct = struct.copy(site_properties = new_sp)
job = pr.create_job(job_type=pr.job_type.Vasp, job_name='SELECTIVEDYNAMICSDOESNTWORK')
job.structure = pi_atoms.pymatgen_to_pyiron(struct_adj)
```

yields
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/tmp/ipykernel_6296/3826973976.py in <cell line: 11>()
      9 struct = struct.copy(site_properties = new_sp)
     10 job = pr.create_job(job_type=pr.job_type.Vasp, job_name='SELECTIVEDYNAMICSDOESNTWORK')
---> 11 job.structure = pi_atoms.pymatgen_to_pyiron(struct_adj)

/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.8/site-packages/pyiron_atomistics/atomistics/structure/atoms.py in pymatgen_to_pyiron(pymatgen_obj)
   3213         pyiron atoms object
   3214     """
-> 3215     return ase_to_pyiron(AseAtomsAdaptor().get_atoms(structure=pymatgen_obj))
   3216 
   3217 

/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.8/site-packages/pymatgen/io/ase.py in get_atoms(structure, **kwargs)
    112                 site_prop = site.properties["selective_dynamics"]
    113                 if site_prop not in [[True, True, True], [False, False, False]]:
--> 114                     raise ValueError(
    115                         "ASE FixAtoms constraint does not support selective dynamics in only some dimensions."
    116                         "Remove the selective dynamics and try again if you do not need them."

ValueError: ASE FixAtoms constraint does not support selective dynamics in only some dimensions.Remove the selective dynamics and try again if you do not need them
```

**To fix:**

I have no idea, since this is inherited from ASE (?). Is it possible to wrangle the job.structure object to accept a pymatgen writer?

I have no issues writing the POSCAR using pymatgen.

### PR DESCRIPTION
**Pull request by ligerzero-ai**
Fixes #786

---
name: Bug fix
about: Submit a pull request that fixes one or more bugs
title: ''
labels: bug
assignees: ''

---

**Summary**

Checks for selective dynamics tags and implements a workaround for ASE not accepting semi-fixed relaxation selective dynamic tags (e.g. [T T F] is not accepted). So, we follow the suggestion by Marvin in #786

Merging this should hopefully fix #786 completely

### CODE REVIEW

**Comment by pmrv** [comment]
Implementation as such looks good.  Please add some specific unit tests, i.e. check that no errors are raised when converting a structure with selective dynamics, the tags are copied correctly and no tags are added when a structure without initial selective dynamics is converted.

**Comment by ligerzero-ai** [comment]
Tests are now implemented - Let me know if anything looks off.

**Comment by pmrv** [comment]
It seems the unit tests won't run until you resolve the merge conflict (it's also ok to rebase and force push, whatever you are comfortable with).  [Codacy](https://app.codacy.com/gh/pyiron/pyiron_atomistics/pullRequest?prid=10277066) also says you missed an import in the tests.

**Comment by ligerzero-ai** [comment]
finally!

Have a look at it, and lmk if anything else needs changing. 

I'll be working on #769 next. Hopefully it is a little less painful.

**Pull request merged**
