### PR TITLE
Try upgrading mp-api

### PR DESCRIPTION
**Pull request by jan-janssen**
There is a conflict with `spglib`.

### CODE REVIEW

**Comment by jan-janssen** [comment]
Because `mp-api` depends on `emmet-core` but `emmet-core` restricts the `spglib` version to below 2.0.0: 
https://github.com/conda-forge/emmet-core-feedstock/blob/main/recipe/meta.yaml#L31

**Comment by jan-janssen** [comment]
```
Looking for: ['aimsgb=0.1.1', 'ase=3.22.1', 'coveralls', 'coverage', 'codacy-coverage', 'defusedxml=0.7.1', 'h5py=3.7.0', 'matplotlib-base=3.6.0', 'mendeleev=0.10.0', 'numpy=1.23.3', 'pandas=1.5.0', 'phonopy=2.15.1', 'pint=0.19.2', 'pyiron_base=0.5.24', 'pymatgen=2022.9.21', 'pyscal=2.10.15', 'scipy=1.9.1', 'seekpath=2.0.1', 'scikit-learn=1.1.2', 'spglib=2.0.1', "ipywidgets[version='<8']", 'mp-api=0.27.5']
[14](https://github.com/pyiron/pyiron_atomistics/actions/runs/3161470087/jobs/5147091623#step:7:15)

[15](https://github.com/pyiron/pyiron_atomistics/actions/runs/3161470087/jobs/5147091623#step:7:16)

[16](https://github.com/pyiron/pyiron_atomistics/actions/runs/3161470087/jobs/5147091623#step:7:17)
Encountered problems while solving:
[17](https://github.com/pyiron/pyiron_atomistics/actions/runs/3161470087/jobs/5147091623#step:7:18)
  - package mp-api-0.27.5-pyhd8ed1ab_0 requires emmet-core >=0.36.4, but none of the providers can be installed
[18](https://github.com/pyiron/pyiron_atomistics/actions/runs/3161470087/jobs/5147091623#step:7:19)
```

**Comment by pmrv** [comment]
Actually even pymatgen already specifies `spglib==1`, not clear to me why this hasn't been a problem yet.  Also searching through the emmet-core code it seems they only access spglib via pymatgen, so I'm unsure as to why they have it as a dependency in the first place.

**Comment by jan-janssen** [comment]
Same issue in https://github.com/pyiron/pyiron_atomistics/pull/795

**Comment by jan-janssen** [comment]
I close this issue in favor of https://github.com/pyiron/pyiron_atomistics/pull/806

**Pull request closed without merging**
