### PR TITLE
Deprecate structure creation methods directly on Project

### PR DESCRIPTION
**Pull request by pmrv**

### CODE REVIEW

**Review by liamhuber — APPROVED** [review]

**Comment by niklassiemer** [comment]
I do not understand how the depreciation hurts that test?! Do we have a problem with the decorator?

**Comment by pmrv** [comment]
No, someone somewhere only check the number of warnings in a unit tests.  Since those change with the PR the test break.

**Comment by niklassiemer** [comment]
@pmrv I took the liberty to fix it directly here.

**Review by jan-janssen — APPROVED** [review]
Looks good to me

**Comment by pmrv** [comment]
> @pmrv I took the liberty to fix it directly here.

Thanks!

**Pull request merged**
