### PR TITLE
Run unittest suite with integration (notebook) environment

### PR DESCRIPTION
**Pull request by niklassiemer**
@samwaseda 
unittests added to the test_integration folder will now run in the full notebook environment and tested on ubuntu with pyhton 3.9

### CODE REVIEW

**Comment by samwaseda** [comment]
I only vaguely remember the discussion (sorry my brain hasn't come back from vacation yet). Was the discussion:

- replace the notebooks by python files, or
- create unit tests in the integration test notebooks?

**Comment by niklassiemer** [comment]
The first one. I.e. converting the notebook into standard unittest/ntegration tests. And maybe a new Notebook to show a few basic things in Sphinx, i.e. more tutorail based.

**Comment by samwaseda** [comment]
So I did the changes. Not sure if I saved the file in the right location though...

**Comment by samwaseda** [comment]
@niklassiemer I guess I did what I was supposed to do. Can you take a look?

**Pull request merged**
