### PR TITLE
Use super in get_structure

### PR DESCRIPTION
**Pull request by pmrv**
Use super instead of hardcoding `GenericInteractive`.  I just want to run the tests on this.

### CODE REVIEW

**Comment by pmrv** [comment]
The codacy nag comes from them not considering multiple inheritance issues.  Since we want to bypass the `get_structure()` from `LammpsBase` and `AtomisticGenericJob` and instead want the one from `GenericInteractive`, this is the correct way to call `super()`.

**Comment by niklassiemer** [comment]
Then, of course, one may ask if our hierarchy is correctly set up since we have to use the method defined multiple layers above...

**Comment by pmrv** [comment]
In the case of multiple inheritance like we have it (see below) it's necessary, since python's default mro is depth-first, but we want breadth first here.

```
AtomisticGeneric
       |
LammpsBase    GenericInteracive
       |                 |
       \                 /
       LammpsInteractive 
```                             

That said, since all our lammps jobs are actually `LammpsInteractive` under the hood, restructuring would be possible.

**Comment by jan-janssen** [comment]
I just looked at the pull request now, from my perspective it is a bit more complex:
```
            GenericJob
            /         \
            |         |
AtomisticGeneric      |
            |      GenericInteracive
     LammpsBase       |   
            |         |
            \        /
       LammpsInteractive 
```
A possible way to resolve this would be:
```
 GenericJob
      |
GenericInteracive
      | 
AtomisticGeneric
      | 
LammpsBase
      | 
LammpsInteractive 
```
This makes a lot of sense when the static jobs also support interactive execution, meaning calculating energies and forces for multiple structures, which should definitely be a goal.

**Comment by pmrv** [comment]
Since it's unlikely that we restructure soon and everything seems to work, I'll merge this as soon as the notebook tests pass.

**Pull request merged**
