### PR TITLE
Wrap phonopy's bandstructure methods

### PR DESCRIPTION
**Pull request by pmrv**
Wraps the band structure methods from phonopy.  I don't store the results in HDF, since they are quick to compute.  Example plot below.

phono

Does anyone have an idea how to get the names of the high symmetry points automatically?  That'd make the axis label a bit prettier.

### CODE REVIEW

**Comment by samwaseda** [comment]
Actually getting the names of the high symmetry points makes it not only prettier, but it gives the x-axis a meaning... Let me see if I can find it.

**Comment by jan-janssen** [comment]
> Does anyone have an idea how to get the names of the high symmetry points automatically? That'd make the axis label a bit prettier.


I guess it should already be in the phonopy source code: 
```
phonon.auto_band_structure(plot=True).show()
```

**Comment by jan-janssen** [comment]
you can try:
```
phonopy._band_structure.labels
```

**Comment by pmrv** [comment]
In the mean time I've tried to use phonopy plot function also and came across this error below, which I then figured out, always comes up when you try to do subplots on our cluster installation.  I seem to remember that this was previously possible, anyone else came across that with subplots before?

```
---------------------------------------------------------------------------
CalledProcessError                        Traceback (most recent call last)
/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/matplotlib/texmanager.py in _run_checked_subprocess(self, command, tex)
    276                                              cwd=self.texcache,
--> 277                                              stderr=subprocess.STDOUT)
    278         except FileNotFoundError as exc:

/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/subprocess.py in check_output(timeout, *popenargs, **kwargs)
    410     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
--> 411                **kwargs).stdout
    412 

/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/subprocess.py in run(input, capture_output, timeout, check, *popenargs, **kwargs)
    511             raise CalledProcessError(retcode, process.args,
--> 512                                      output=stdout, stderr=stderr)
    513     return CompletedProcess(process.args, retcode, stdout, stderr)

CalledProcessError: Command '['latex', '-interaction=nonstopmode', '--halt-on-error', '/u/zora/.cache/matplotlib/tex.cache/4cd8318b7870ed0b2cb40a1e2fbe7319.tex']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

RuntimeError                              Traceback (most recent call last)
/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/IPython/core/formatters.py in __call__(self, obj)
    339                 pass
    340             else:
--> 341                 return printer(obj)
    342             # Finally look for special method names
    343             method = get_real_method(obj, self.print_method)

/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/IPython/core/pylabtools.py in <lambda>(fig)
    246 
    247     if 'png' in formats:
--> 248         png_formatter.for_type(Figure, lambda fig: print_figure(fig, 'png', **kwargs))
    249     if 'retina' in formats or 'png2x' in formats:
    250         png_formatter.for_type(Figure, lambda fig: retina_figure(fig, **kwargs))

/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/IPython/core/pylabtools.py in print_figure(fig, fmt, bbox_inches, **kwargs)
    130         FigureCanvasBase(fig)
    131 
--> 132     fig.canvas.print_figure(bytes_io, **kw)
    133     data = bytes_io.getvalue()
    134     if fmt == 'svg':

/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/matplotlib/backend_bases.py in print_figure(self, filename, dpi, facecolor, edgecolor, orientation, format, bbox_inches, pad_inches, bbox_extra_artists, backend, **kwargs)
   2191                            else suppress())
   2192                     with ctx:
-> 2193                         self.figure.draw(renderer)
   2194 
   2195                     bbox_inches = self.figure.get_tightbbox(

/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/matplotlib/artist.py in draw_wrapper(artist, renderer, *args, **kwargs)
     39                 renderer.start_filter()
     40 
---> 41             return draw(artist, renderer, *args, **kwargs)
     42         finally:
     43             if artist.get_agg_filter() is not None:

/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/matplotlib/figure.py in draw(self, renderer)
   1862             self.patch.draw(renderer)
   1863             mimage._draw_list_compositing_images(
-> 1864                 renderer, self, artists, self.suppressComposite)
   1865 
   1866             renderer.close_group('figure')

/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/matplotlib/image.py in _draw_list_compositing_images(renderer, parent, artists, suppress_composite)
    129     if not_composite or not has_images:
    130         for a in artists:
--> 131             a.draw(renderer)
    132     else:
    133         # Composite any adjacent images together

/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/matplotlib/artist.py in draw_wrapper(artist, renderer, *args, **kwargs)
     39                 renderer.start_filter()
     40 
---> 41             return draw(artist, renderer, *args, **kwargs)
     42         finally:
     43             if artist.get_agg_filter() is not None:

/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/matplotlib/cbook/deprecation.py in wrapper(*inner_args, **inner_kwargs)
    409                          else deprecation_addendum,
    410                 **kwargs)
--> 411         return func(*inner_args, **inner_kwargs)
    412 
    413     return wrapper

/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/matplotlib/axes/_base.py in draw(self, renderer, inframe)
   2745             renderer.stop_rasterizing()
   2746 
-> 2747         mimage._draw_list_compositing_images(renderer, self, artists)
   2748 
   2749         renderer.close_group('axes')

/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/matplotlib/image.py in _draw_list_compositing_images(renderer, parent, artists, suppress_composite)
    129     if not_composite or not has_images:
    130         for a in artists:
--> 131             a.draw(renderer)
    132     else:
    133         # Composite any adjacent images together

/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/matplotlib/artist.py in draw_wrapper(artist, renderer, *args, **kwargs)
     39                 renderer.start_filter()
     40 
---> 41             return draw(artist, renderer, *args, **kwargs)
     42         finally:
     43             if artist.get_agg_filter() is not None:

/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/matplotlib/axis.py in draw(self, renderer, *args, **kwargs)
   1164         ticks_to_draw = self._update_ticks()
   1165         ticklabelBoxes, ticklabelBoxes2 = self._get_tick_bboxes(ticks_to_draw,
-> 1166                                                                 renderer)
   1167 
   1168         for tick in ticks_to_draw:

/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/matplotlib/axis.py in _get_tick_bboxes(self, ticks, renderer)
   1090         """Return lists of bboxes for ticks' label1's and label2's."""
   1091         return ([tick.label1.get_window_extent(renderer)
-> 1092                  for tick in ticks if tick.label1.get_visible()],
   1093                 [tick.label2.get_window_extent(renderer)
   1094                  for tick in ticks if tick.label2.get_visible()])

/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/matplotlib/axis.py in <listcomp>(.0)
   1090         """Return lists of bboxes for ticks' label1's and label2's."""
   1091         return ([tick.label1.get_window_extent(renderer)
-> 1092                  for tick in ticks if tick.label1.get_visible()],
   1093                 [tick.label2.get_window_extent(renderer)
   1094                  for tick in ticks if tick.label2.get_visible()])

/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/matplotlib/text.py in get_window_extent(self, renderer, dpi)
    900 
    901         with cbook._setattr_cm(self.figure, dpi=dpi):
--> 902             bbox, info, descent = self._get_layout(self._renderer)
    903             x, y = self.get_unitless_position()
    904             x, y = self.get_transform().transform((x, y))

/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/matplotlib/text.py in _get_layout(self, renderer)
    287         _, lp_h, lp_d = renderer.get_text_width_height_descent(
    288             "lp", self._fontproperties,
--> 289             ismath="TeX" if self.get_usetex() else False)
    290         min_dy = (lp_h - lp_d) * self._linespacing
    291 

/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py in get_text_width_height_descent(self, s, prop, ismath)
    226             fontsize = prop.get_size_in_points()
    227             w, h, d = texmanager.get_text_width_height_descent(
--> 228                 s, fontsize, renderer=self)
    229             return w, h, d
    230 

/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/matplotlib/texmanager.py in get_text_width_height_descent(self, tex, fontsize, renderer)
    421         else:
    422             # use dviread.
--> 423             dvifile = self.make_dvi(tex, fontsize)
    424             with dviread.Dvi(dvifile, 72 * dpi_fraction) as dvi:
    425                 page, = dvi

/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/matplotlib/texmanager.py in make_dvi(self, tex, fontsize)
    309                 self._run_checked_subprocess(
    310                     ["latex", "-interaction=nonstopmode", "--halt-on-error",
--> 311                      texfile], tex)
    312             for fname in glob.glob(basefile + '*'):
    313                 if not fname.endswith(('dvi', 'tex')):

/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/matplotlib/texmanager.py in _run_checked_subprocess(self, command, tex)
    288                     prog=command[0],
    289                     tex=tex.encode('unicode_escape'),
--> 290                     exc=exc.output.decode('utf-8'))) from exc
    291         _log.debug(report)
    292         return report

RuntimeError: latex was not able to process the following string:
b'lp'

Here is the full report generated by latex:
This is pdfTeX, Version 3.14159265-2.6-1.40.18 (TeX Live 2017/TeX Live for SUSE Linux) (preloaded format=latex)
 restricted \write18 enabled.
entering extended mode
(/u/zora/.cache/matplotlib/tex.cache/4cd8318b7870ed0b2cb40a1e2fbe7319.tex
LaTeX2e <2017-04-15>
Babel <3.10> and hyphenation patterns for 12 language(s) loaded.
(/usr/share/texmf/tex/latex/base/article.cls
Document Class: article 2014/09/29 v1.4h Standard LaTeX document class
(/usr/share/texmf/tex/latex/base/size10.clo))
(/usr/share/texmf/tex/latex/type1cm/type1cm.sty)
(/usr/share/texmf/tex/latex/cm-super/type1ec.sty
(/usr/share/texmf/tex/latex/base/t1cmr.fd))

! LaTeX Error: File `helvet.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name: 
! Emergency stop.
<read *> 
         
l.7 \usepackage
               {type1ec}^^M
No pages of output.
Transcript written on 4cd8318b7870ed0b2cb40a1e2fbe7319.log.
```

**Comment by jan-janssen** [comment]
> In the mean time I've tried to use phonopy plot function also and came across this error below, which I then figured out, always comes up when you try to do subplots on our cluster installation. I seem to remember that this was previously possible, anyone else came across that with subplots before?

@muh-hassani  maybe ?

**Comment by pmrv** [comment]
> > In the mean time I've tried to use phonopy plot function also and came across this error below, which I then figured out, always comes up when you try to do subplots on our cluster installation. I seem to remember that this was previously possible, anyone else came across that with subplots before?
> 
> @muh-hassani maybe ?

Sorry, just checked again, the error is related to subplots, but only appears after one tries to call the phonopy plot function once.  So it seems phonopy messes up the matplotlib config somehow and it's not on us.

**Comment by pmrv** [comment]
Updated picture attached.  Rebase + force push because of the numpy issue.  It's in one axis instead of one axis per contiguous path as in phonopy, but I didn't want to spend too much time reinventing the wheel.

Comparable plot from phonopy [here @ nist](https://www.ctcms.nist.gov/potentials/iprPy/notebook/phonon.html).

phono

**Comment by max-hassani** [comment]
@pmrv and @jan-janssen,
Sorry, I did not understand well, that the issue is relevant to the phonopy package installed on the cluster or it is reproducible on any machine? I have just updated all the packages, there was no new release for phonopy. I will check when was the last update. If you think it is necessary, I can do a downgrade?

**Comment by pmrv** [comment]
> @pmrv and @jan-janssen,
> Sorry, I did not understand well, that the issue is relevant to the phonopy package installed on the cluster or it is reproducible on any machine? I have just updated all the packages, there was no new release for phonopy. I will check when was the last update. If you think it is necessary, I can do a downgrade?

It's all good, phonopy's plotting function doesn't work on our setup (it seems to need a latex dep we don't have), but I think that was always the case.  For a moment I thought that subplots in matplotlib are generally broken, but they aren't only after using phonopy.  There's no need to change anything right now, sorry for the confusion!

**Review by jan-janssen — APPROVED** [review]
Looks good to me

**Pull request merged**
