### PR TITLE
Just testing to get Windows CI running again

### PR DESCRIPTION
**Pull request by niklassiemer**
Revert to be279d0d52d501b3b6683bbda39c3ca18cd66ba3

### CODE REVIEW

**Comment by pmrv** [comment]
If I remember correctly the windows CI ended up taking hours and got cancelled before I merged it.  I had not investigated why though.  Since I don't have a windows machine accessible can you check whether running the tests locally on a windows machine takes as much time as on CI?

**Comment by niklassiemer** [comment]
No they run fast for me. I will update my windoof test suite conda again to make sure this is not related to some other package being updated. 
However, I got a file not found error on "tests/static/lammps_test_files/get_structure_test.tar.gz", probably since I started the tests in the wrong directory. We should make this independent, though.
Another issue, we should run the integration tests in `pyiron_base` with all OS not only linux, I will make a PR for that.

**Comment by pmrv** [comment]
Aha, no I think I didn't include those files in #241. :/

EDIT: No `get_structure_test.tar.gz` is correctly located in `test/static/lammps_test_files`.

**Comment by niklassiemer** [comment]
Might be, however, I tested with the current master and I have these files... In addition, the windows tests should then just fail and not run forever!?

**Pull request closed without merging**
