### PR TITLE
np.matrix.trace() returns float

### PR DESCRIPTION
**Pull request by jan-janssen**

### CODE REVIEW

**Comment by jan-janssen** [comment]
``` 
np.matrix.trace(np.eye(3)) == 3.0
> True
```

**Comment by jan-janssen** [comment]
https://numpy.org/doc/stable/reference/generated/numpy.matrix.trace.html and https://numpy.org/doc/stable/reference/generated/numpy.trace.html

**Comment by pmrv** [comment]
Even safer against numerical noise would probably be `not np.isclose(..., 3)`, but if the intent of that check is to test for the identity matrix I would actually prefer `np.isclose(prism.R, np.eye(3))`.

**Comment by samwaseda** [comment]
> Even safer against numerical noise would probably be `not np.isclose(..., 3)`, but if the intent of that check is to test for the identity matrix I would actually prefer `np.isclose(prism.R, np.eye(3))`.

I was about to write exactly the same thing XD, although it should be with `.all()`: `np.isclose(prism.R, np.eye(3)).all()`

**Comment by jan-janssen** [comment]
`rtol=0`, `atol=1e-08` - as a function

**Comment by jan-janssen** [comment]
@samwaseda and @pmrv Any more suggestions? otherwise I would like to merge this pull request.

**Comment by samwaseda** [comment]
Fine by me

**Pull request merged**
