### PR TITLE
Rename master to main

### PR DESCRIPTION
**Pull request by liamhuber**
Also for a couple references to github.com/pyiron/pyiron/tree/master, which worked because github kindly redirects us, but should still be main now.

### CODE REVIEW

**Review by jan-janssen — APPROVED** [review]
Looks good to me

**Comment by jan-janssen** [comment]
It seems the migration on `pyiron_base` is slowing down the unit tests not only in `pyiron_base` but also here on `pyiron_atomistics`.

**Comment by liamhuber** [comment]
@jan-janssen I think we should also update some external links, e.g. appveyor

- https://ci.appveyor.com/api/projects/status/wfdgqkxca1i19xcq/branch/master?svg=true
- https://ci.appveyor.com/project/pyiron-runner/pyiron/branch/master

Right now I'm still fighting with "access denied" errors there so I can't yet confirm that this got updated to main.

Over on coveralls I took a look at pyiron_base, and there we need to manually tell them to start looking at "main", and will need to update our links accordingly

**Comment by jan-janssen** [comment]
> @jan-janssen I think we should also update some external links, e.g. appveyor
> 
> * https://ci.appveyor.com/api/projects/status/wfdgqkxca1i19xcq/branch/master?svg=true
> * https://ci.appveyor.com/project/pyiron-runner/pyiron/branch/master

I guess we no longer use `appveyor` as now all our tests are executed by the Github CI, previously we used `appveyor` for tests on windows.

**Comment by jan-janssen** [comment]
> Over on coveralls I took a look at pyiron_base, and there we need to manually tell them to start looking at "main", and will need to update our links accordingly

Ok, I try to do this after work.

**Comment by liamhuber** [comment]
> > @jan-janssen I think we should also update some external links, e.g. appveyor
> > 
> > * https://ci.appveyor.com/api/projects/status/wfdgqkxca1i19xcq/branch/master?svg=true
> > * https://ci.appveyor.com/project/pyiron-runner/pyiron/branch/master
> 
> I guess we no longer use `appveyor` as now all our tests are executed by the Github CI, previously we used `appveyor` for tests on windows.

Ok, then we can leave it updated and remove these from the documentation entirely in a separate PR.

**Comment by liamhuber** [comment]
> > Over on coveralls I took a look at pyiron_base, and there we need to manually tell them to start looking at "main", and will need to update our links accordingly
> 
> Ok, I try to do this after work.

Don't worry about it, I'm pretty sure I misspoke -- it looks like coveralls is running on each branch (since we do call it on the branches' CI) so once the push CI gets run on main I think it will all auto-update.

Links still need to be updated in our docs, but that can be done as part of these PRs

**Comment by liamhuber** [comment]
> > > Over on coveralls I took a look at pyiron_base, and there we need to manually tell them to start looking at "main", and will need to update our links accordingly
> > 
> > 
> > Ok, I try to do this after work.
> 
> Don't worry about it, I'm pretty sure I misspoke -- it looks like coveralls is running on each branch (since we do call it on the branches' CI) so once the push CI gets run on main I think it will all auto-update.
> 
> Links still need to be updated in our docs, but that can be done as part of these PRs

Turns out I didn't misspeak, it did need to be updated on coveralls. But I just had to go into the repo settings there an "resync", so it was easy.

**Pull request merged**
