### PR TITLE
Use state instead of Settings

### PR DESCRIPTION
**Pull request by liamhuber**
A surprising amount of the time that just meant getting rid of the Settings import, as it was unused. I also snuck in a couple other unused import removals and some encoding info additions here and there, depending on the repo.

### CODE REVIEW

**Comment by niklassiemer** [comment]
You are a bit early, since the `state` PR is not yet released to conda 😃

**Comment by liamhuber** [comment]
> You are a bit early, since the `state` PR is not yet released to conda 😃

😆 yep, we're looking at it simultaneously

**Review by samwaseda — APPROVED** [review]
I'm not particularly happy with the fact that there's no test, but other than that it looks good to me. :)

**Comment by liamhuber** [comment]
> I'm not particularly happy with the fact that there's no test, but other than that it looks good to me. :)

We'll, the basic state stuff is tested over in base. It's true though that I didn't add any special tests, and Marvin did indeed track down a state related (but maybe not state or caused?) issue. I don't know how to conveniently link issues on my phone in the app though, so you'll just have to go look for it 🤣

**Pull request merged**
