### PR TITLE
Remove six depedency

### PR DESCRIPTION
**Pull request by pmrv**
The only thing we still used it for was `string_types`, which is just `(str,)` on python 3.

### CODE REVIEW

**Comment by jan-janssen** [comment]
I guess we just have to be aware that with this change we are removing Python 2.7 compatibility. 
https://stackoverflow.com/questions/11301138/how-to-check-if-variable-is-string-with-python-2-and-3-compatibility

And `six` is generally `noarch` and therefore available for all python version https://anaconda.org/conda-forge/six/files

**Comment by pmrv** [comment]
We haven't been advertising python 2.7 compatibility for a about a year now, so personally I feel that's fine.

**Comment by pmrv** [comment]
Ah, the notebook issue is not fixed yet it seems. Since this change is unlikely to affect anything there, I'd just go ahead and merge it today anyways.

**Comment by jan-janssen** [comment]
I guess we first have to merge https://github.com/pyiron/pyiron_atomistics/pull/348

**Review by jan-janssen — APPROVED** [review]
Looks good to me - @pmrv  once the tests pass we should merge this.

**Pull request merged**
