### PR TITLE
fix SPHInX restarts

### PR DESCRIPTION
**Pull request by freyso**
restarts from waves or density must rewrite initialGuess group

### CODE REVIEW

**Comment by freyso** [comment]
I am lost with how debug the failed notebook, because it seems the SPHInX job has not run properly. Is there any way of running the failing notebook interactively using this version of pyiron (i.e. from the current branch), to see what might have happened?

**Comment by jan-janssen** [comment]
> I am lost with how debug the failed notebook, because it seems the SPHInX job has not run properly. Is there any way of running the failing notebook interactively using this version of pyiron (i.e. from the current branch), to see what might have happened?

You can run any branch on mybinder (alternatively to testing locally): 
[Binder](https://mybinder.org/v2/gh/pyiron/pyiron_atomistics/fix_restart_sphinx)
```
[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/pyiron/pyiron_atomistics/fix_restart_sphinx)
```

**Review by skatnagallu — COMMENTED** [review]
Looks good to me.

**Review by samwaseda — APPROVED** [review]
I tried to find a problem but it looks good to me. The only one thing is that `def restart` is now somewhat a bit lengthy (for the python standard). At some point we should probably think about reorganising it.

**Comment by freyso** [comment]
OK, I am done with fixing. For the test coverage decrease, not sure if this is a problem. I personally don't think it makes sense to implement unit testing for the restart, as this would require a successfully completed  sphinx job (incl. density + waves sxb files).
@jan-janssen - any thoughts/concerns about this?
From my side, this can be merged.

**Comment by samwaseda** [comment]
Since some people need it (i.e. me) I merged it

**Pull request merged**
