### PR TITLE
Run benchmark tests in separate step with continue-on-error true

### PR DESCRIPTION
**Pull request by niklassiemer**

### CODE REVIEW

**Comment by pmrv** [comment]
Are the results still visible with this or do we always have to manually check then if they passed or not?  I understand that #288 is annoying, but if they actually fail for real it should be very obvious.

**Comment by niklassiemer** [comment]
The main difference is actually only that the other tests are not stopped due to a failure in the benchmarks. The benchmark tests are now an additional step in the unittests (we do not need to rebuild). For the decision if it is a fail, the overall workflow is judged and, therefore, it should after result in an red X in our overview... (I would prefer a yellow !)

**Comment by pmrv** [comment]
> The main difference is actually only that the other tests are not stopped due to a failure in the benchmarks. The benchmark tests are now an additional step in the unittests (we do not need to rebuild). For the decision if it is a fail, the overall workflow is judged and, therefore, it should after result in an red X in our overview... (I would prefer a yellow !)

Sounds good then!

**Comment by niklassiemer** [comment]
Converted to draft, since I want to resolve the windows CI issue first.

**Comment by niklassiemer** [comment]
Closed in favor of #313.

**Pull request closed without merging**
