### PR TITLE
Fix parsing of Bader charges

### PR DESCRIPTION
**Pull request by sudarsan-surendralal**
Now compatible with all version of `bader` (https://theory.cm.utexas.edu/henkelman/code/bader/) that even stores the output as a pickle

### CODE REVIEW

**Comment by sudarsan-surendralal** [comment]
@jyang2009, can you please try running the following code with this new branch and see it it works? I've explained how to run pyiron with a specific github branch [here](https://github.com/pyiron/pyiron_atomistics/issues/590#issuecomment-1107819600).
```python
import numpy as np
%matplotlib inline
import matplotlib.pylab as plt
from pyiron import Project


pr = Project("test_bader")


cell = np.eye(3) * 5
cell[2, 2] = 7
theta = (104.52 / 2.) * np.pi / 180.0
r = 0.9572
x = r  * np.cos(theta)
H_pos = np.ones((2, 3)) 
H_pos[:, 2] = x
a = ((r**2 - x**2) / 2.) ** 0.5
H_pos[:, [0, 1]] = a
H_pos[-1][:2] *= -1.0
positions = np.ones((3, 3)) * 0.5
basis = pr.create_atoms(["O", "H", "H"], scaled_positions=positions, cell=cell)
basis.positions[basis.select_index("H")] =  H_pos + basis.positions[basis.select_index("O")[0]]


ham = pr.create_job(pr.job_type.Vasp, "job_vasp", delete_existing_job=True)
ham.structure = basis
ham.calc_static(retain_charge_density=True)
ham.input.incar["LAECHG"] = True
ham.run()

print(ham["output/generic/dft/bader_charges"])
```

**Comment by jyang2009** [comment]
Hi Sudarsan@sudarsan-surendralal, I've tried the code as you suggested. However when I print the bader charges it shows "None". Not sure it's because of the job not running correctly or because of pyiron. Maybe we can look at this together some other time? Thanks a lot for the help!

**Comment by sudarsan-surendralal** [comment]
@jyang2009, can you pull the changes and try again please?

**Comment by jyang2009** [comment]
Hi Sudarsan, I've tried the updated version. It didn't work on either the water molecule example or my Mg(OH)2 case. The .CUBE file is not written. The error message is:
File "/u/jyang/Program/pyiron_atomistics/pyiron_atomistics/atomistics/volumetric/generic.py", line 357, in write_cube_file
    write_cube(filename, self._atoms, data=self.total_data)
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.8/site-packages/ase/io/cube.py", line 43, in write_cube
    fileobj.write(comment)
AttributeError: 'str' object has no attribute 'write'

Do you have any idea how this could be? Let me know. Thanks a lot for your help with this.

**Comment by jyang2009** [comment]
Hi Sudarsan, I tried the last version you committed. The writing error is solved. However the bader analysis part still cannot read the .CUBE files correctly. The error I got (for the water molecule case) is:
File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.8/site-packages/pybader/io/cube.py", line 108, in read
    charge[x, y, idx:idx + idx_inc] = line
ValueError: could not broadcast input array from shape (16,) into shape (96,)

Have you tried again the water molecule case? I wonder if you would get the same error.

**Comment by sudarsan-surendralal** [comment]
> Hi Sudarsan, I tried the last version you committed. The writing error is solved. However the bader analysis part still cannot read the .CUBE files correctly. The error I got (for the water molecule case) is: File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.8/site-packages/pybader/io/cube.py", line 108, in read charge[x, y, idx:idx + idx_inc] = line ValueError: could not broadcast input array from shape (16,) into shape (96,)
> 
> Have you tried again the water molecule case? I wonder if you would get the same error.

This is indeed very strange. To me everything from the pyiron side seems okay. The CUBE files are indeed written correctly. It seems that this `pybader` package installed on our cluster is unable to read these files. In fact, I'm not even sure why we have this package installed. @tnecnivkcots, can you please uninstall package 'pybader' on our cluster? As far as I know, this does not seem to be a dependency on any pyiron packages. I have a hunch that this will solve our issue.

**Comment by tnecnivkcots** [comment]
As I can see pybader is installed on our cluster with pip. Additionally we have bader as a conda package installed.
I will remove pybader.

**Comment by tnecnivkcots** [comment]
pybader is now uninstalled.

**Comment by sudarsan-surendralal** [comment]
> pybader is now uninstalled.

Thank you! But now we can't access the 'bader' executable from conda on the terminal. Do you know where this is located and why we can't access this?

**Comment by jan-janssen** [comment]
Just a word of caution, it is not recommended to mix both `pip` and `conda` as it can easily result in conflicts in the environment. For most pip packages it is commonly easy to just create a conda package to simplify the administration of the environment and prevent conflicts. I just created the package for `pybader` https://anaconda.org/conda-forge/pybader 

To resolve the issue mentioned here it is most likely required to reinstall `bader` as both packages contain an executable named `bader`.

**Comment by jan-janssen** [comment]
I ran a quick check `conda list | grep pypi`: 

```
coscine                   0.5.2                    pypi_0    pypi
prettytable               2.4.0                    pypi_0    pypi
```

Both packages are also available on conda-forge https://anaconda.org/conda-forge/coscine and https://anaconda.org/conda-forge/prettytable so I would highly recommend installing them via conda-forge to keep the environment clean and prevent these kinds of issues.

**Comment by tnecnivkcots** [comment]
Thank you for your help @jan-janssen. I was also confused by the packages, installed with pip.
I will uninstall them and install them with conda (or in our case we use mamba).

**Comment by tnecnivkcots** [comment]
I have uninstalled the pypi packages and installed them with mamba.
@sudarsan-surendralal does it now work, as you expect?

**Comment by sudarsan-surendralal** [comment]
> I have uninstalled the pypi packages and installed them with mamba. @sudarsan-surendralal does it now work, as you expect?

It still can't find the executable from conda. So when I try the following command, it doesn't work:

```bash
bader
>> bader: Command not found.
``` 

I checked `/cmmc/u/system/SLES12/soft/pyiron/dev/anaconda3/bin` and I can't find the bader executable either

**Comment by tnecnivkcots** [comment]
I will check for some help online.

**Comment by tnecnivkcots** [comment]
I do not know, how the binary files are usually created and can not find any helpful information online, except of building it with conda. But usually it is sufficient to run out `compile-python-packages.sh` script and make aftwerwards a `conda clean`.
@jan-janssen, @pmrv can you give me some hints?

**Comment by pmrv** [comment]
I've confirmed that the package as downloaded from conda contains the bader executable and it runs on the cluster.  I would hope that reinstalling then fixes the problem. :|

**Comment by tnecnivkcots** [comment]
I have installed bader already newly with conda (mamba), after I removed it with pip (and the also installed conda package disappeared).
If I try to remove it now, it does not work.

**Comment by tnecnivkcots** [comment]
Maybe bader is not even installed as a conda package and just a nominal member ("Karteileiche").
If I execute `find -depth -name bader*` in the directory `/u/system/soft/pyiron/dev/anaconda3` I get no `./lib/python3.8/site-packages/bader` directory:
```
./lib/python3.8/site-packages/pymatgen/command_line/bader_caller.py
./lib/python3.8/site-packages/pymatgen/command_line/__pycache__/bader_caller.cpython-38.pyc
./lib/python3.8/site-packages/pyiron_atomistics/dft/bader.py
./lib/python3.8/site-packages/pyiron_atomistics/dft/__pycache__/bader.cpython-38.pyc
./lib/python3.8/site-packages/gpaw/utilities/bader.py
./lib/python3.8/site-packages/gpaw/utilities/__pycache__/bader.cpython-38.pyc
./lib/python3.8/site-packages/ase/io/bader.py
./lib/python3.8/site-packages/ase/io/__pycache__/bader.cpython-38.pyc
./conda-meta/bader-1.0.4-h1990efc_1.json
```
If I make the same search with for example calphy `find -depth -name calphy*`, in the same directory, I get the bin and for example the `./lib/python3.8/site-packages/calphy`.
```
./bin/calphy_kernel
./bin/calphy
./lib/python3.8/site-packages/calphy
./lib/python3.8/site-packages/pyiron_atomistics/calphy
./lib/python3.8/site-packages/calphy-1.0.3.dist-info
./conda-meta/calphy-1.0.3-pyhd8ed1ab_1.json
```

And I guess this could be solved by deleting the remained `./conda-meta/bader-1.0.4-h1990efc_1.json`.
What do you think @pmrv ?

**Comment by pmrv** [comment]
Yeah, kick out the `.json` file manually, then reinstall using conda.  I'd guess removing with pip removed the executable, but didn't remove the json, so conda thinks it's still installed.

**Comment by jan-janssen** [comment]
> Yeah, kick out the `.json` file manually, then reinstall using conda. I'd guess removing with pip removed the executable, but didn't remove the json, so conda thinks it's still installed.

I guess this is one of the issues when combining pip and conda.

**Comment by tnecnivkcots** [comment]
After ` rm -v conda-meta/bader-1.0.4-h1990efc_1.json` to remove it, `mamba install bader` returns after a few seconds back to the common comand line. The common mamba logo does not show up. A `conda list | grep bader` show no output.

It seems, that mamba is not working properly now. Today at 10 am, I made the typical updates of conda packages and everything went fine.
If I now try to execute a `mamba update --all` it returns back to the common cli, so also no mamba logo.

**Comment by jan-janssen** [comment]
You could try `conda clean --all` this cleans all the caches. Otherwise does `conda update --all` work?

**Comment by tnecnivkcots** [comment]
That also does not work. After `conda clean --all` I get 
```
There are no unused tarball(s) to remove
Will remove 1 index cache(s).
Proceed ([y]/n)? y

WARNING: cannot remove, file permissions: /u/system/SLES12/soft/pyiron/dev/anaconda3/pkgs/cache
There are no unused package(s) to remove
There are no tempfile(s) to remove.
There are no logfile(s) to remove.
```

And if I use conda to install or update some packages it hungs up in a loop of collecting package metadata and solving the environment.
```
Collecting package metadata (current_repodata.json): done
Solving environment: -
The environment is inconsistent, please check the package plan carefully
The following packages are causing the inconsistency:

  - conda-forge/noarch::pyiron==0.4.6=pyhd8ed1ab_0
  - conda-forge/noarch::pyiron_atomistics==0.2.47=pyhd8ed1ab_0
  - conda-forge/linux-64::pymatgen==2022.5.26=py38h43d8883_0
  - conda-forge/noarch::moviepy==1.0.3=pyhd8ed1ab_0
  - conda-forge/noarch::matminer==0.7.8=pyhd8ed1ab_0
  - conda-forge/noarch::aimsgb==0.1.0=pyhd8ed1ab_1
  - conda-forge/noarch::imageio-ffmpeg==0.4.7=pyhd8ed1ab_0
  - conda-forge/linux-64::ffmpeg==4.4.1=hd7ab26d_2
  - conda-forge/linux-64::mamba==0.23.3=py38h1abaa86_1
  - conda-forge/noarch::pyiron_contrib==0.1.3=pyhd8ed1ab_0
  - conda-forge/linux-64::vtk==9.1.0=no_osmesa_py38h66b282c_101               failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: |
The environment is inconsistent, please check the package plan carefully
The following packages are causing the inconsistency:

  - conda-forge/noarch::pyiron==0.4.6=pyhd8ed1ab_0
  - conda-forge/noarch::pyiron_atomistics==0.2.47=pyhd8ed1ab_0
  - conda-forge/linux-64::pymatgen==2022.5.26=py38h43d8883_0
  - conda-forge/noarch::moviepy==1.0.3=pyhd8ed1ab_0
  - conda-forge/noarch::matminer==0.7.8=pyhd8ed1ab_0
  - conda-forge/noarch::aimsgb==0.1.0=pyhd8ed1ab_1
  - conda-forge/noarch::imageio-ffmpeg==0.4.7=pyhd8ed1ab_0
  - conda-forge/linux-64::ffmpeg==4.4.1=hd7ab26d_2
  - conda-forge/linux-64::mamba==0.23.3=py38h1abaa86_1
  - conda-forge/noarch::pyiron_contrib==0.1.3=pyhd8ed1ab_0
  - conda-forge/linux-64::vtk==9.1.0=no_osmesa_py38h66b282c_101 
  ```

A solution could be the first or second answer in [here on stackoverflow](https://stackoverflow.com/questions/63734508/stuck-at-solving-environment-on-anaconda)
What do you think

**Comment by tnecnivkcots** [comment]
should we maybe continue this discussion in another repository? But which one? I have no overview in our djungle of repositories.

**Comment by tnecnivkcots** [comment]
Maybe on gitlab: https://gitlab.mpcdf.mpg.de/pyiron/pyiron_cluster_documentation?

**Comment by jan-janssen** [comment]
> should we maybe continue this discussion in another repository? But which one? I have no overview in our djungle of repositories.

I do not think I can help here, it could be a permissions error which is causing this, but that depends on how Muhammad managed the environment after I left. So debugging it remotely is hard. Did he provide you with any documentation, what to look for? I remember that we had specific scripts to build the Python modules and keep the permissions fixed but that was some time ago.

**Comment by tnecnivkcots** [comment]
The documentation is in the gitlab repo,: https://gitlab.mpcdf.mpg.de/pyiron/pyiron_cluster_documentation
There is also a bash script, I wrote lasst year for updating conda packages. Everything else is documented in the Wiki of that repo, but there is no information about how to handle a situation like this, except of a list of people to consult.

So the next step is asking Muhammad, if he knows this behavior of mamba/conda and additionally reading what the command `conda config --set channel_priority flexible` exactly do (and which other options are there which could be set).

**Comment by tnecnivkcots** [comment]
Ok, the command `conda config --set channel_priority ...`, which was suggested on stackoverflow does not help.

**Comment by tnecnivkcots** [comment]
I want to move the discussion about our conda environment to gitlab. Please follow this [link](https://gitlab.mpcdf.mpg.de/pyiron/pyiron_cluster_documentation/-/issues/1).

**Comment by jan-janssen** [comment]
> It seems, that mamba is not working properly now. Today at 10 am, I made the typical updates of conda packages and everything went fine. If I now try to execute a `mamba update --all` it returns back to the common cli, so also no mamba logo.

To me this sounds similar like https://github.com/mamba-org/mamba/issues/1708

**Comment by tnecnivkcots** [comment]
Thank you @jan-janssen. I have answered on [gitlab](https://gitlab.mpcdf.mpg.de/pyiron/pyiron_cluster_documentation/-/issues/1).

**Comment by tnecnivkcots** [comment]
Hey colleagues,
still no news. but I am working on it.
If you want to know the status, [checkout the issue on gitlab](https://gitlab.mpcdf.mpg.de/pyiron/pyiron_cluster_documentation/-/issues/1).

**Comment by jan-janssen** [comment]
> To me this sounds similar like [mamba-org/mamba#1708](https://github.com/mamba-org/mamba/issues/1708)

So the suggested fix: 
```
conda install conda=4.12
```
Did not work for you?

**Comment by tnecnivkcots** [comment]
`conda install ` generally does not work. There is always the loop of

```
Collecting package metadata (current_repodata.json): done
Solving environment: -
The environment is inconsistent, please check the package plan carefully
The following packages are causing the inconsistency:

  - conda-forge/noarch::pyiron==0.4.6=pyhd8ed1ab_0
  - conda-forge/noarch::pyiron_atomistics==0.2.47=pyhd8ed1ab_0
  - conda-forge/linux-64::pymatgen==2022.5.26=py38h43d8883_0
  - conda-forge/noarch::moviepy==1.0.3=pyhd8ed1ab_0
  - conda-forge/noarch::matminer==0.7.8=pyhd8ed1ab_0
  - conda-forge/noarch::aimsgb==0.1.0=pyhd8ed1ab_1
  - conda-forge/noarch::imageio-ffmpeg==0.4.7=pyhd8ed1ab_0
  - conda-forge/linux-64::ffmpeg==4.4.1=hd7ab26d_2
  - conda-forge/linux-64::mamba==0.23.3=py38h1abaa86_1
  - conda-forge/noarch::pyiron_contrib==0.1.3=pyhd8ed1ab_0
  - conda-forge/linux-64::vtk==9.1.0=no_osmesa_py38h66b282c_101               failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: |
The environment is inconsistent, please check the package plan carefully
The following packages are causing the inconsistency:

  - conda-forge/noarch::pyiron==0.4.6=pyhd8ed1ab_0
  - conda-forge/noarch::pyiron_atomistics==0.2.47=pyhd8ed1ab_0
  - conda-forge/linux-64::pymatgen==2022.5.26=py38h43d8883_0
  - conda-forge/noarch::moviepy==1.0.3=pyhd8ed1ab_0
  - conda-forge/noarch::matminer==0.7.8=pyhd8ed1ab_0
  - conda-forge/noarch::aimsgb==0.1.0=pyhd8ed1ab_1
  - conda-forge/noarch::imageio-ffmpeg==0.4.7=pyhd8ed1ab_0
  - conda-forge/linux-64::ffmpeg==4.4.1=hd7ab26d_2
  - conda-forge/linux-64::mamba==0.23.3=py38h1abaa86_1
  - conda-forge/noarch::pyiron_contrib==0.1.3=pyhd8ed1ab_0
  - conda-forge/linux-64::vtk==9.1.0=no_osmesa_py38h66b282c_101 
  ```

and after some hours/days the installation fails.

**Comment by jan-janssen** [comment]
This is not a loop, conda is iterating over different sources: 
```
Collecting package metadata (current_repodata.json): done
```
vs.
```
Collecting package metadata (repodata.json): done
```

**Comment by tnecnivkcots** [comment]
Independent from what it is, I can not install anything. I already tried to set a conda environment up, with similar packages, but just without the conflicting packages and I saw there are some more conflicts.
Probably to solve this conflicts, I have to renew the conda environment.

**Comment by jan-janssen** [comment]
Just run and wait for it to iterate over the different sources: 

> So the suggested fix:
> 
> ```
> conda install conda=4.12
> ```

**Comment by tnecnivkcots** [comment]
I ran that command on our cluster. I will report the result. Until now it looks unchanged.
Next week, when I have finished some other urgent tasks, I will try to set up a conda evironment inside a container to check, if it is even possible to set up a conda environment with all these packages without conflicts. Then I can extract the version numbers and have a chance to compare.

EDIT: I have started executing the suggested command today at about 11 am. I do not know when it finishes.

**Comment by tnecnivkcots** [comment]
Despite of all conflicts between the conda packages, the command ran through and conda  4.12 is now installed.
mamba is also now updated to 0.24.0 and bader is installed with version 1.0.4

But there are still conflicts in the conda environment and I hope that will not lead to the next problem in some time.

**Comment by sudarsan-surendralal** [comment]
@tnecnivkcots, thank you for fixing this. Since this was an issue with the conda packages, these new changes seem unnecessary to me. So I close this.

**Pull request closed without merging**
