### PR TITLE
Move some of the structure plotting functions from contrib

### PR DESCRIPTION
**Pull request by pmrv**
They were previously defined on the `TrainingContainer` over in contrib, but I have added also `distances` to plot a plain histogram of nearest neighbor distances.

Corresponding PR to contrib once this is through.

### CODE REVIEW

**Comment by Leimeroth** [comment]
So TrainingContainers plotting interface should inherit from this than?

**Comment by pmrv** [comment]
Yeah, that's how I was planning it.  These plotting functions would be purely concerned with structural data and the training container ones would then only add things related to energies, forces, etc.

**Review by Leimeroth — APPROVED** [review]
I like the idea. If some errors occur down the line we should fix them there.

**Comment by pmrv** [comment]
I didn't want to pull in seaborn for just one plot, so I put it in an `ImportAlarm`.  @niklassiemer are we tracking our opt deps somewhere?

**Comment by pmrv** [comment]
I also remembered to update the change log. :')

**Review by jan-janssen — APPROVED** [review]
Looks good to me

**Pull request merged**
