### PR TITLE
Make Methfessel Paxton default in SPHInX

### PR DESCRIPTION
**Pull request by samwaseda**
Since Methfessel-Paxton is now available in SPHInX I made it the default behaviour in pyiron.

### CODE REVIEW

**Comment by sudarsan-surendralal** [comment]
There is a danger to setting this as the default. The Methfessel-Paxton scheme is not recommended for semi-conductors and insulators where you could end up with occupancies less than 0 (see the [discussion](https://www.vasp.at/wiki/index.php/ISMEAR) on the VASP wiki). There is no way of knowing if a structure is metallic or not beforehand and therefore wouldn't something like the Fermi/Gaussian type smearing be better?

**Comment by samwaseda** [comment]
But shouldn't we follow the default behaviour in VASP? (cf. [this page](https://www.vasp.at/wiki/index.php/ISMEAR))

**Comment by sudarsan-surendralal** [comment]
> 
> 
> But shouldn't we follow the default behaviour in VASP? (cf. [this page](https://www.vasp.at/wiki/index.php/ISMEAR))

Generally yes, but in this case, we need to consider the possibility that the VASP default may not be the right option. But I'm not sure.

**Comment by samwaseda** [comment]
ok but I guess it's a bigger problem that SPHInX and VASP have different default settings, isn't it?

**Comment by sudarsan-surendralal** [comment]
> 
> 
> ok but I guess it's a bigger problem that SPHInX and VASP have different default settings, isn't it?

Ah yes, then what you implemented here is correct (both VASP and SPHINX now have the same default parameters). But I guess people working with semiconductors/insulators should be aware of this.

**Review by sudarsan-surendralal — APPROVED** [review]

**Pull request merged**
