### PR TITLE
Use .content rather than .project_hdf5

### PR DESCRIPTION
**Pull request by pmrv**
This allows .output to work with Sphinx jobs that use strange output format.

### CODE REVIEW

**Comment by jan-janssen** [comment]
> This allows .output to work with Sphinx jobs that use strange output format.

Does this break LAMMPS and VASP?

**Comment by pmrv** [comment]
> > This allows .output to work with Sphinx jobs that use strange output format.
> 
> Does this break LAMMPS and VASP?

The only difference between .content and .project_hdf5 is that the former tries to `to_object()` any `DataContainers` it finds, but otherwise returns the same, so I can't see why it would make problems.  Technically .content raises KeyErrors instead of ValueErrors which is what caused the test failures on the weekend, but since .output anyway always silenced those to None, no outside code should depend on this.

@samwaseda Can you add a test case for #1508?

**Comment by jan-janssen** [comment]
@pmrv Should we adjust the pyiron table to also use `content` rather than `output` ?

**Comment by pmrv** [comment]
> @pmrv Should we adjust the pyiron table to also use `content` rather than `output` ?

You mean the predefined datamining functions?  Yes, that would make sense.

**Review by jan-janssen — APPROVED** [review]
Looks good to me. Once @samwaseda confirms it fixes his issues, I guess we should merge this and a release a new minor version.

**Comment by jan-janssen** [comment]
@samwaseda Can you confirm this is working for SPHInx? I would like to release a new `pyiron_atomistics` version today.

**Review by samwaseda — APPROVED** [review]
I guess it's fine.

**Pull request merged**
