### PR TITLE
Create general input output for `AtomisticGenericJob`

### PR DESCRIPTION
**Pull request by samwaseda**
Centralize `to_hdf` and `from_hdf` in `AtomisticGenericJob`.

### CODE REVIEW

**Comment by niklassiemer** [comment]
Why in `AtomisticGenericJob` and not in `GenericJob`?

**Comment by samwaseda** [comment]
> Why in `AtomisticGenericJob` and not in `GenericJob`?

Because the idea of storing everything inside `self.input` and `self.output` is currently not compatible with `ParallelMaster`. When the implementation is done for `AtomisticGenericJob` we can move forward to `GenericJob`

**Comment by samwaseda** [comment]
So this story turned out to be more complicated, as `AtomisticsParallelMaster` was actually derived from `AtomisticGenericJob`... Is there a possibility to set priority for the parent classes?

**Comment by pmrv** [comment]
You can use `super(Parent, self).method` to call `method` that is defined on `Parent` or any of it's super classes, effectively allowing you to skip the direct superclass(es) of `type(self)`.  But I'm not sure what you're trying to do.

I've found (older) explanation [here](https://rhettinger.wordpress.com/2011/05/26/super-considered-super/) which made me realize, we actually use it a bit wrong especially in the case of job classes.  Iirc Ray had a talk on youtube on this topic also.

**Pull request closed without merging**
