### PR TITLE
Allow to fix some axes in Murnaghan

### PR DESCRIPTION
**Pull request by pmrv**
This simply changes the job generator to apply the strain only along axes that are in `murn.input['axes']`.

### CODE REVIEW

**Review by prince-mathews — APPROVED** [review]
Everything looks alright to me

**Comment by pmrv** [comment]
I've just noticed a bug, where the structure returned from `get_structure` is scaled wrongly to the equilibrium volume.

**Comment by prince-mathews** [comment]
Should I merge it?

**Comment by pmrv** [comment]
I've tested it and it should work, but I was still trying to figure why the unit tests are not run for this PR.  Any idea @niklassiemer ?

**Comment by pmrv** [comment]
Failing test seems to come from a sphinx notebook, so I'll merge it anyway.

**Pull request merged**
